parameters:
  kommunikatisten_schedule.author.email: 'effeff67@kommunikatisten.net'

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  _instanceof:
    Contao\CoreBundle\Framework\FrameworkAwareInterface:
      calls:
        - [ "setFramework", [ "@contao.framework" ] ]

    Symfony\Component\DependencyInjection\ContainerAwareInterface:
      calls:
        - [ "setContainer", [ "@service_container" ] ]

  Kommunikatisten\ContaoScheduleBundle\:
    resource: '../../'
    exclude:
      - '../../DependencyInjection/'
      - '../../Resources/'
      - '../../DoNotTrack/'
      - '../../Entity'

  Kommunikatisten\ContaoScheduleBundle\Controller\:
    resource: '../../Controller/'
    tags: [ 'controller.service_arguments','kommunikatisten_schedule' ]

  Kommunikatisten\ContaoScheduleBundle\Controller\CourseScheduleController:
    tags:
      - { name: contao.frontend_module, category: kommunikatisten, template: ctrl_schedule, type: course_schedule }

  Kommunikatisten\ContaoScheduleBundle\Controller\CourseListController:
    tags:
      - { name: contao.frontend_module, category: kommunikatisten, template: ctrl_course_list, type: course_list }

  Kommunikatisten\ContaoScheduleBundle\Controller\CourseReaderController:
    tags:
      - { name: contao.frontend_module, category: kommunikatisten, template: ctrl_course_reader, type: course_reader }

  Kommunikatisten\ContaoScheduleBundle\Controller\BE\BackendCourseController:
    tags:
      - { name: contao.backend_module, category: kommunikatisten, template: course, type: be_komm_course }

  Kommunikatisten\ContaoScheduleBundle\Controller\BE\BackendSubjectController:
    tags:
      - { name: contao.backend_module, category: kommunikatisten, template: subject, type: be_komm_course }

  Kommunikatisten\ContaoScheduleBundle\Controller\BE\BackendTeacherController:
    tags:
      - { name: contao.backend_module, category: kommunikatisten, template: teacher, type: be_komm_course }

  # services
  Kommunikatisten\ContaoScheduleBundle\Service\:
    resource: '../../Service/'
    tags: [ 'controller.service_arguments','kommunikatisten_schedule' ]
  Kommunikatisten\ContaoScheduleBundle\Service\TeacherBackendService:
    tags:
      - { name: contao.backend_service, category: kommunikatisten, template: teacher, type: be_komm_course }

