parameters:
  kommunikatisten_schedule.author.email: 'effeff67@kommunikatisten.net'

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  _instanceof:
    Contao\CoreBundle\Framework\FrameworkAwareInterface:
      calls:
        - [ "setFramework", [ "@contao.framework" ] ]

    Symfony\Component\DependencyInjection\ContainerAwareInterface:
      calls:
        - [ "setContainer", [ "@service_container" ] ]

  Kommunikatisten\ContaoScheduleBundle\:
    resource: '../../'
    exclude:
      - '../../DependencyInjection/'
      - '../../Entity/'
      - '../../Resources/'

  Kommunikatisten\ContaoScheduleBundle\Controller\:
    resource: '../../Controller/'
    tags: [ 'controller.service_arguments','kommunikatisten_schedule' ]

  Kommunikatisten\ContaoScheduleBundle\Controller\TestController:
    tags:
      - { name: contao.frontend_module, category: miscellaneous, template: mod_kom_test, type: komm_test }
  Kommunikatisten\ContaoScheduleBundle\Controller\ScheduleController:
    tags:
      - { name: contao.frontend_module, category: schedule, template: ctrl_schedule, type: komm_schedule }
